#!/bin/bash -l

export PATH=/usr/local/bin:$PATH

DAYS_TO_KEEP=14
ES_ENABLED=$(nubis-metadata NUBIS_FLUENT_ES_ENDPOINT)

if [ "$ES_ENABLED" != "" ]; then
  # Builder a logstash filter for old indices
  FILTER=$(cat << EOF
[{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":$DAYS_TO_KEEP},{"filtertype":"pattern","kind":"prefix","value":"logstash"}]
EOF
)
  # check if we have something to expire
  if /usr/local/bin/curator_cli --host localhost --port 8080 show_indices --filter_list "$FILTER" 2>/dev/null ; then
    # delete away
    /usr/local/bin/curator_cli --host localhost --port 8080 delete_indices --filter_list "$FILTER"
  else
    # Nothing to expire
    exit 0
  fi
fi
