#!/bin/bash -l

DAYS_TO_KEEP=14
ES_ENABLED=$(nubis-metadata NUBIS_FLUENT_ES_ENDPOINT)

if [ "$ES_ENABLED" != "" ]; then
  curator --loglevel ERROR --quiet --host localhost --port 8080 delete indices --prefix logstash --timestring '%Y.%m.%d' --time-unit days --older-than $DAYS_TO_KEEP
fi
